name: blacktiger

services:
  web:
    build:
      context: .
      args:
        WC_URL: ${WC_URL}
        WC_CONSUMER_KEY: ${WC_CONSUMER_KEY}
        WC_CONSUMER_SECRET: ${WC_CONSUMER_SECRET}
    container_name: blacktiger-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:4070:3000"
    env_file:
      - .env.local
