services:
  web:
    build: .
    ports:
      - "3002:3000"
    env_file:
      - .env.local
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./lib:/app/lib
      - ./store:/app/store
      - ./public:/app/public
      - ./tailwind.config.ts:/app/tailwind.config.ts
